### ISSUE TITLE
Wrong crate name in readme

### ISSUE THREAD

**Issue by williamdes** [bpetit/rs-docker-sync#1]
Bonjour 🇫🇷 

The right name is: `docker-sync`

https://crates.io/crates/docker-sync

**Comment by williamdes** [comment]
The `extern crate` from https://github.com/bpetit/rs-docker-sync/commit/5e0b0d5439ad2d1d3341736335052601754441ca are wrong they should be `extern crate docker_sync;`

**Comment by bpetit** [comment]
Hi !

Thanks for noticing that, I've rushed the first description of the crate as I wanted to use it quickly, sorry for those inconsistencies.
I'll fix that.
